### ISSUE TITLE
How do we make delegate harvesting to the latest version node a valid vote in the Harlock fork?

### ISSUE THREAD

**Issue by h-gocchi** [NemProject/nis#13]
NEM (NIS1) voting and hard fork (Harlock)

https://hackmd.io/@syndicate/governance
https://hackmd.io/@xymbassador/rJoa_afwK

■ Issue
NIS1 node update = voting is not very advanced.

■ What we want to know
Therefore, increasing the delegate harvesting to the nodes that are updated to the latest NIS1 node version 0.6.98 and increasing the node importance will have some effect.

However.
- We need at least 24 hours of delegation before and after the Harlock fork.
- Vested balance is important, and depending on the amount held, it may not be effective.

So, we would like to know more about the conditions, such as how much XEM we need to delegate now to become a valid vote, taking into account the vested balance.

And once this issue below is resolved, we hope that the community can promote delegate harvesting to the latest nodes.
https://github.com/NemProject/nis/issues/12

**Comment by h-gocchi** [comment]
Reference :
https://nemkit.oe-jpy.com/VestedSchedule

**Comment by h-gocchi** [comment]
NEM Wallet Windows, Linux, Mac x NIS1 v0.6.98 (Harlock-enabled node) seems to succeed in transactions, only the Universal version wallet fails.

**Comment by Jaguar0625** [comment]
If you are moving funds from an exchange account to a new account, the funds will need to vest. As a consequence, the sooner the funds are moved the better. It does not matter when delegation starts. Vesting is independent to whether or not a fund is actively harvesting.

Consequently, if you have an off-exchange account that is not delegating, funds will likely already be fully vested. Delegating or harvesting with these accounts will have the biggest immediate impact.

**Comment by h-gocchi** [comment]
Thanks for your cooperation!
It's important for the vested balance to be kept in the wallet for a period of time, not on the exchange.
We also found that the larger the fund, the faster we could get a vested balance.
